#!/usr/bin/env bash
#this is a script that display to infinity and beyond indefinitely
#this is a script that displays to infinity and beyound indefinitely

for  (( i=1; i>0; i++  ))
do
echo; "to infinity and beyond
sleep 2
done
