#!/usr/bin/env bash
#runs nginx as nginx
pkill apache2
chown nginx:nigix /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
